function OffPulses2StimFile(filePath, pre, post, sr)
% Generates stim_file for Spyking circus GUI from *OffPulses.txt file
% generated by OffPulses.m code.
%
% INPUTS
%
% 'filepath' is the path to folder with the file. Ends with '\' or '/'.
% 'pre' is the time before the stimulus [s]
% 'post' is the time after the stimulus [s] 
% 'sr' is the samplign rate if the recording [Hz]

cd(filePath);
filename = dir('*OffPulses.txt');
expName = dir('*spiketimes*.mat');
expName = expName.name;
dotPos = strfind(expName,'.spike');
expName = expName(1:dotPos-1);
pulses = load([filePath,filename.name]);

rep_begin_time = cell(length(pulses),1);
rep_end_time = rep_begin_time;

for i=1:length(pulses)
    rep_begin_time{i} = [pulses(i) - pre]'*sr;
    rep_end_time{i} = [pulses(i) + post]'*sr;
end

save([filePath,expName,'.stim'],'rep_begin_time','rep_end_time');

